import { Move } from '@/types/pokemon';

export const MOVES_MAP: { [key: string]: Move } = {
    pound: {
        id: 'pound',
        name: 'Pound',
        type: 'normal',
        power: 40,
        pp: 35,
        maxPP: 35,
        accuracy: 100,
    },
    leer: {
        id: 'leer',
        name: 'Leer',
        type: 'normal',
        power: 0,
        pp: 30,
        maxPP: 30,
        accuracy: 100,
    },
    quickattack: {
        id: 'quickattack',
        name: 'Quick Attack',
        type: 'normal',
        power: 40,
        pp: 30,
        maxPP: 30,
        accuracy: 100,
    },
    scratch: {
        id: 'scratch',
        name: 'Scratch',
        type: 'normal',
        power: 40,
        pp: 35,
        maxPP: 35,
        accuracy: 100,
    },
    growl: {
        id: 'growl',
        name: 'Growl',
        type: 'normal',
        power: 0,
        pp: 40,
        maxPP: 40,
        accuracy: 100,
    },
    ember: {
        id: 'ember',
        name: 'Ember',
        type: 'fire',
        power: 40,
        pp: 25,
        maxPP: 25,
        accuracy: 100,
    },
    mudslap: {
        id: 'mudslap',
        name: 'Mud-Slap',
        type: 'ground',
        power: 20,
        pp: 10,
        maxPP: 10,
        accuracy: 100,
    },
    bite: {
        id: 'bite',
        name: 'Bite',
        type: 'dark',
        power: 60,
        pp: 25,
        maxPP: 25,
        accuracy: 100,
    },
    howl: {
        id: 'howl',
        name: 'Howl',
        type: 'normal',
        power: 0,
        pp: 20,
        maxPP: 20,
        accuracy: 100,
    },
    tailwhip: {
        id: 'tailwhip',
        name: 'Tail Whip',
        type: 'normal',
        power: 0,
        pp: 30,
        maxPP: 30,
        accuracy: 100,
    },
    stringshot: {
        id: 'stringshot',
        name: 'String Shot',
        type: 'bug',
        power: 0,
        pp: 40,
        maxPP: 40,
        accuracy: 100,
    },
    poisonpowder: {
        id: 'poisonpowder',
        name: 'Poison Powder',
        type: 'poison',
        power: 0,
        pp: 35,
        maxPP: 35,
        accuracy: 75,
    },
    tackle: {
        id: 'tackle',
        name: 'Tackle',
        type: 'normal',
        power: 40,
        pp: 35,
        maxPP: 35,
        accuracy: 100,
    },
};
